### ISSUE TITLE
Setup expectations for ocfl-py

### ISSUE THREAD

**Issue by awoods** [zimeon/ocfl-py#18]
When running `ocfl-validate.py` on a OCFL object, I get the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/awoods/.local/lib/python3.7/site-packages/ocfl/data/validation-errors.json'
```
Is there some additional setup command I should be running in order for ocfl-py to have the entire environment it is expecting?

**Comment by zimeon** [comment]
Doh! Thanks for pointing that out @awoods -- I forgot to install the list of errors in the setup script.

0.0.3 on pypi should now fix this -- https://pypi.org/project/ocfl-py/0.0.3/

**Comment by awoods** [comment]
I believe I updated my ocfl-py by:
```
pip3 install ocfl-py
```
`ocfl-validate.py` is installed in: "/home/awoods/.local/bin/ocfl-validate.py"
It is not clear to me how to see which version of `ocfl-validate.py` that is... but in any case, the following shows no result:
```
cd ~/.local/lib
find . -name 'validation-errors.json'
```
..and I am still getting the error when running: "ocfl-validate.py <some-ocfl-object-dir>":
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/awoods/.local/lib/python3.7/site-packages/ocfl/data/validation-errors.json'
```

**Comment by zimeon** [comment]
Hmmm.... did you do

```
pip3 install --upgrade ocfl-py
```

I just tried and install with a fresh virtualenv and couldn't replicate the problem

**Comment by zimeon** [comment]
Solved.
